### PR TITLE
cast memories frequency to avoid warning on comparison

### PR DESCRIPTION
**Pull request by orthagh**
fix theses warnings:

```
*** PHP Warning(2): A non-numeric value encountered
  Backtrace :
  ...nventory/inc/inventorycomputerlib.class.php:406
  ...ry/inc/inventorycomputerinventory.class.php:577 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory/inc/inventoryruleimport.class.php:790 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1436                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1461                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:378 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:126 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
2017-10-31 09:43:28 [6@riy10161.bind.log.intra.laposte.fr]
  *** PHP Warning(2): A non-numeric value encountered
  Backtrace :
  ...nventory/inc/inventorycomputerlib.class.php:407
  ...ry/inc/inventorycomputerinventory.class.php:577 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory/inc/inventoryruleimport.class.php:790 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc/rule.class.php:1436                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc/rulecollection.class.php:1461                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:378 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:126 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
```

### CODE REVIEW

**Comment by ddurieux** [comment]
If I remember, we have the Mb or Gb on some inventory but not sure and that's why we have the problem. Have you the possibility to get the XML ?
The code will works, but I prefer verify and fix the source of the problem too ;)

**Comment by orthagh** [comment]
Yes, we had some random values before.
Here is a screenshot of my dev glpi database:
image

@g-bougard says me the recent versions of agent now send integer values but we still could have some text strings in db like the screenshot so we need to cast to prevent warning

**Comment by orthagh** [comment]
> Have you the possibility to get the XML ?

Yes, but in the case i found, i'm sure the issue was in the db part

**Comment by ddurieux** [comment]
Ok so ok for me ;)

**Pull request merged**
