### PR TITLE
Update files headers

### LINKED ISSUE #2255: old URLs in asciidoc
There are several links in the sources pointing to forge.fusioninventory.org - which hasn't been updated for over 2 years.

Shouldn't they be pointing here or to the main fusioninventory.org site?

### LINKED ISSUE #2369: Update files header
Hello,

On files header, the copyright still en d to 2016.
There is always a link to http://forge.fusioninventory.org which is a dead end.

Should be nice to clean all headers :-)
GLPI tool could be used (https://github.com/glpi-project/glpi/blob/9.2/bugfixes/tools/modify_headers.pl)

I can help for this.

Regards,
Anael

### PR DESCRIPTION
**Pull request by AnaelMobilia**
Fix #2369 : update files headers
  - Copyright update to 2018
  - addition of GLPI's tool for update copyright
Fix #2255 : old urls

### CODE REVIEW

**Comment by ddurieux** [comment]
Hi, your script has modified the oui.sql and so break the SQL query on install, you you check it please?

**Comment by AnaelMobilia** [comment]
@ddurieux I have never done a squash, I will try do do that !

**Comment by AnaelMobilia** [comment]
@ddurieux If you can provide help for this... I succesly soft reset and commit, but then I always have a conflict with my remote (github) repository where I can't push my squashed version... :-(

**Comment by ddurieux** [comment]
Normal, if you had squash, you must push with arg `-f`

**Comment by AnaelMobilia** [comment]
@ddurieux Thanks ! (I have to update too git version... github... :-)).
The squash is done !

Regards,
Anael

**Comment by AnaelMobilia** [comment]
@ddurieux @trasher  Is it something specific required to merge this PR ?

Regards,
Anael

**Comment by AnaelMobilia** [comment]
Hello @btry 

I used the [basic template provided by the FSF](https://www.gnu.org/licenses/agpl-3.0.en.html#howto) for licensing files.
As this, all kind of files can be tagged on the same way, using a standard and recognized template.

For the @author specification, imho, Github history is a really better substainable source of information (this information is, when it's present on the file, only the file creator name, not all contributors on the file).

Regards,
Anael

**Comment by btry** [comment]
> For the @author specification, imho, Github history is a really better substainable source of information
i agree for this one, and I think it is not the most important one.

but globally, the annotation give ability to produce good documentation (apigen or similar).

Also I noticed you dropped lines related to class description. This is nice to keep, in a dedicated block (IMO) because many classes have cryptic name. Removing these lines leads to a loss of information, which may be useful for new contributors (this is a big plugin).

**Comment by AnaelMobilia** [comment]
@btry You're good : I didn't see that some file have comments on the middle of the licence header.
I will update soon the PR (I update the title to WIP).

Regards,
Anael

**Comment by AnaelMobilia** [comment]
This PR is now too old, closing it.

**Pull request closed without merging**
