### PR TITLE
unclean_cross_side_scripting_deep of commande

### PR DESCRIPTION
**Pull request by lermit4**

### CODE REVIEW

**Comment by wawax** [comment]
Hi @lermit4 
Thanks for the PR. Could you provide a use case where the action is not correclty managed, so I can reproduce the issue ?

**Comment by lermit4** [comment]
echo "write in file" >> c:\TEMP\HELLO.txt
the ">" is replaced by '&lt;', '&gt;' in the command line and windows or linux doesn't like this

**Comment by wawax** [comment]
thank you. I reproduce your issue !

**Comment by wawax** [comment]
thank you. I reproduce your issue !

**Comment by ddurieux** [comment]
I have moved your code in another file + add a test.
Thanks for your contribution and sorry for the too long delay (https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2532)

**Pull request closed without merging**
