### PR TITLE
Solve [GLPI 9.4.4] Search doesn't work

### PR DESCRIPTION
**Pull request by cyrilus**
solve issue #2869

### CODE REVIEW

**Comment by trasher** [comment]
Maybe related to https://github.com/glpi-project/glpi/pull/6388 ; fixed in core. Please test.

**Comment by dani** [comment]
Backporting only commit https://github.com/glpi-project/glpi/commit/cc63e97d618f4fd179ac1aa620766c47c3f80be2 doesn't seem to fix the issue. But I'm not sure if the issue is on FI side, as there're issues also searching in tickets (like searching in task description with some other criteria)

**Comment by ddurieux** [comment]
Can you give all columns you display and the search you do to have the error? 

With that, I will try to reproduce

**Comment by cyrilus** [comment]
HI,

I display last date of fusion inventory  and search for last date of 
fusion inventory is Today

Hope it help

Le 10/10/2019 à 13:57, David Durieux a écrit :

**Comment by boisrobe** [comment]
I try this fix https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2876/files#diff-383a5ed2dc99e099faf4477d0318e8c3 and my global search works now

**Comment by ddurieux** [comment]
The GLPI core fix or the fix of this pull request?

**Comment by boisrobe** [comment]
> The GLPI core fix or the fix of this pull request?

Don't sur what this mean (i'am french with my poor english ;-) )

GLPI 9.4.4 Copyright (C) 2015-2019 Teclib' and contributors
FusionInventory 9.4+2.1 - Copyleft © 2010-2019 by FusionInventory Team

The fix i apply is the file change of the hook.php that is describe in this thread.
https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2876/files

Sorry if i wrote a the wrong place. I just want to confirm it resolve the issue

**Comment by arkanium** [comment]
Hello,

I can confirm that i have the same problem described.

I tryed update core then update FI plugin and the search in computer and global don't work.
I had to revert back due to production impact.


it occurs on : 
https://glpi.[fqdn]/front/search.php?globalsearch=[...]
and
https://glpi.[fqdn]/front/computer.php

To reproduce

1 upgrade GLPI (FI plugin disabled) - update from zip or git clone same result
2 global search and computer search filter work
3 update & activate FI plugin -from zip or git clone
4 Global search and computer search filter don't work
5 disable Fi plugin -> search work again

Columns displayed from computer and filter
image

For the global search the "computer" section never appear on the result page.

image

before update informations (same result after except for glpi version and FI plugin version)

```
GLPI 9.4.3 ( => /var/www/glpi)   Installation mode: TARBALL
--
Server
Operating system: Linux glpi   4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64   
PHP 7.0.33-0+deb9u6 apache2handler   (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler,   apc, apcu,           calendar,   ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash,   iconv, imap, json, ldap, libxml, mbstring,           mysqli,   mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap,   sockets, ssh2, standard, sysvmsg, sysvsem,           sysvshm,   tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)   Setup:   max_execution_time="600" memory_limit="128M"   post_max_size="8M" safe_mode=""   session.save_handler="files"           upload_max_filesize="2M"      
Software: Apache/2.4.25 (Debian)   (Apache/2.4.25 (Debian) Server at XXXXXX Port 443)           Mozilla/5.0   (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0   
Server Software: MySQL Community   Server (GPL)           
Server   Version: 5.7.28           
Server   SQL Mode:            
Parameters:   XXXX@localhost/glpi           Host   info: Localhost via UNIX socket              

mysqli extension is installed   
ctype extension is installed   
fileinfo extension is installed   
json extension is installed   
mbstring extension is installed  
 iconv extension is installed   
zlib extension is installed   
curl extension is installed   
gd extension is installed   
simplexml extension is installed   
xml extension is installed   
ldap extension is installed   
imap extension is installed   
Zend OPcache extension is   installed   
APCu extension is installed   
xmlrpc extension is installed   
CAS extension is installed   
exif extension is installed   

Database version seems correct   (5.7.28) - Perfect!   /var/www/glpi/files/_log : OK   /var/www/glpi/config : OK   /var/www/glpi/files : OK   /var/www/glpi/files/_dumps : OK   /var/www/glpi/files/_sessions : OK   /var/www/glpi/files/_cron : OK   /var/www/glpi/files/_graphs : OK   /var/www/glpi/files/_lock : OK   /var/www/glpi/files/_plugins : OK   /var/www/glpi/files/_tmp : OK   /var/www/glpi/files/_cache : OK   /var/www/glpi/files/_rss : OK   /var/www/glpi/files/_uploads : OK   /var/www/glpi/files/_pictures : OK   

Libraries
htmLawed version 1.2.4 in   (/var/www/glpi/lib/htmlawed)   phpmailer/phpmailer version 6.0.7   in (/var/www/glpi/vendor/phpmailer/phpmailer/src)   simplepie/simplepie version 1.5.2   in (/var/www/glpi/vendor/simplepie/simplepie/library)   tecnickcom/tcpdf version 6.2.26 in   (/var/www/glpi/vendor/tecnickcom/tcpdf)   michelf/php-markdown in   (/var/www/glpi/vendor/michelf/php-markdown/Michelf)   true/punycode in   (/var/www/glpi/vendor/true/punycode/src)   iamcal/lib_autolink in   (/var/www/glpi/vendor/iamcal/lib_autolink)   sabre/vobject in   (/var/www/glpi/vendor/sabre/vobject/lib)   zendframework/zend-cache in   (/var/www/glpi/vendor/zendframework/zend-cache/src)   zendframework/zend-i18n in   (/var/www/glpi/vendor/zendframework/zend-i18n/src)   zendframework/zend-serializer in   (/var/www/glpi/vendor/zendframework/zend-serializer/src)   monolog/monolog in   (/var/www/glpi/vendor/monolog/monolog/src/Monolog)   sebastian/diff in   (/var/www/glpi/vendor/sebastian/diff/src)   elvanto/litemoji in   (/var/www/glpi/vendor/elvanto/litemoji/src)   symfony/console in   (/var/www/glpi/vendor/symfony/console)   leafo/scssphp in   (/var/www/glpi/vendor/leafo/scssphp/src)   phpCas version 1.3.3 in   (/usr/share/php)

LDAP directories
Server: 'XXXXXXX', Port: '389',   BaseDN: 'dc=XXXX,dc=XXXX', Connection filter:                   '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))',   RootDN: 'CN=XXXXXX', Use TLS: none

SQL replicas
Not active

Notifications
Way of sending emails: SMTP (XXXXX)
Mails receivers
 
Plugins list
addressing           Name: Adressage IP                   Version: 2.8.0      State: Enabled           webapplications      Name: Applications Web               Version: 2.6.0      State: Enabled           databases            Name: Bases de données               Version: 2.2.1      State: Enabled           shellcommands        Name: Commandes Shell                Version: 2.3.0      State: Enabled           accounts             Name: Comptes                        Version: 2.5.0      State: Enabled           formcreator          Name: Form Creator                   Version: 2.8.6      State: Enabled           fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled           manufacturersimports   Name: Imports fabricants               Version: 2.2.0      State:   Enabled           datainjection        Name: Injection de fichiers          Version: 2.7.0      State: Enabled           mreporting           Name: Plus de rapports               Version: 1.6.1      State: Enabled           dashboard            Name: Tableau de bord                Version: 0.9.8      State: Enabled
```

is there any log or else i can provide you for investigations ?

**Comment by ddurieux** [comment]
I have no error with the patch of the GLPI core

**Pull request merged**
