### PR TITLE
ADD: retrieve cron tasks from agent

### PR DESCRIPTION
**Pull request by aperret-dcs**

### CODE REVIEW

**Comment by g-bougard** [comment]
Hi @aperret-dcs 
what's the purpose of this PR and which agents are concerned ? As far I know, Fusioninventory agent is not concerned.

**Comment by ddurieux** [comment]
The PR for Agent will be pushed in the week ;)

**Comment by ddurieux** [comment]
Use https://github.com/aperret-dcs/fusioninventory-for-glpi/commits/feature/retrieveCronTasks

**Comment by hugotomasi** [comment]
Hello, do you have any idea when this PR will be merged ? Thanks in advance :)

**Comment by ddurieux** [comment]
This week-end, I'm preparing the next version of the plugin ;)

**Comment by ddurieux** [comment]
See #3308

**Pull request closed without merging**
