### PR TITLE
Master+update volume for rmovable media

### PR DESCRIPTION
**Pull request by dethegeek**
This patch allow import of removable volumes, previously filtered.

Code commented out because I think it may be useful to build an admin preference in the plugin's settings panel.

### CODE REVIEW

**Comment by ddurieux** [comment]
Can you rebase with master please? I have made modifications with travis (unit tests).
``` git rebase master ```

**Comment by btry** [comment]
Hi

should be better now :)

**Comment by ddurieux** [comment]
you have modification defined in title + modifications not linked ... + more than 250 commits :/ it's just too complex

**Comment by dethegeek** [comment]
My fork was too old. I'll recreate the patch from a fresh copy of the
project.

2016-02-09 21:55 GMT+01:00 David Durieux <notifications@github.com>:

**Comment by ddurieux** [comment]
Thanks, sorry for the delay to merge it, it's a little my fault :(

**Pull request closed without merging**
