### PR TITLE
 Do not import MAC when Port is Aggregate; fixes #2258

### LINKED ISSUE #2258: HP Switches Bridge Aggregation Ports Issue
Hello guys,

I have some HP switches on my network, LLDP is active in all switches.
My topology is as follows:
My Core Network is two HP 5130 switch in IRF, the 5130 is a comware 7 switch. My edge switches are HP 1920 switches (Comware 5) and these are plugged in the core via bridge aggreagtion port (LACP Dynamic).
Well i configured the LLDP protocol in the members ports of the bridge aggregation as TxRx interface, both on edge switches and on core switch.
In the Neighbor Summary of the switches, the conncetion information appears correctly. 
As you can see on the print screen of edge switch neighbor Summary.
edge_switch

And core switch neighbor Summary.

core_switch

both switches identify the connected ports, but in the fusioninventory, the aggregaton appears as a HUB connection. Print of core switch ports in GLPI.

fusion_core_swicth

the same occurs in the edge switch.
Only one port of the bridge aggregation appears as connected to a switch in the fusioninvetory and the bridge aggregation interface appears connected to a HUB.

I apologize for bad English. I'm waiting for an answer. Thank you

### PR DESCRIPTION
**Pull request by trasher**
Just a PR for patch proposed in https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2258.

### CODE REVIEW

**Comment by Wolvverine** [comment]
Or maybe better:
`
      # Do not import MAC when Port is Aggregate
      if ($pfNetworkPort->getValue('iftype') == '161' || $pfNetworkPort->getValue('iftype') == '135'  || $pfNetworkPort->getValue('iftype') == '53') {
        return;
      }

`

**Comment by ddurieux** [comment]
I prefer the iftype than the 'ifdescr'. Ok for the type 161 (aggrega). For others, not sure add it in code, perhaps have an option to define it yourself, like create ports have type xxx in general options

**Comment by ddurieux** [comment]
```
propVirtual(53),    -- proprietary virtual/internal
l2vlan (135),       -- Layer 2 Virtual LAN using 802.1Q
```
for 53 perhaps, for 135 less sure :p

**Comment by trasher** [comment]
Sounds like proposed fix is not correct. Since I'm not going to work on this PR, I'm closing it.

**Comment by Wolvverine** [comment]
On Fortigate for All internal VLAN interfaces:

```
<PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>d4:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>d0:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>5c:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>dc:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>f0:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>5c:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>0c:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>28:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>c0:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>28:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>5c:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
              <MAC>00:xx:xx:xx:xx:xx:xx:xx</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>4849</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>0.00 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>vlanname</IFNAME>
          <IFNUMBER>xx</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>xxxxxxxx</IFOUTOCTETS>
          <IFPORTDUPLEX>0</IFPORTDUPLEX>
          <IFSPEED>1000000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>135</IFTYPE>
          <IP>xxx.xxx.xxx.xxx</IP>
          <IPS>
            <IP>xxx.xxx.xxx.xxx</IP>
          </IPS>
          <MAC>xx:xx:xx:xx:xx:xx</MAC>
</PORT>
```
All ports have the same MAC address, and one IP address and IFTYPE 135.

And all this ports are in fusioninventory show as one:
image

**Comment by Wolvverine** [comment]
And another similar problem, but port is not aggregate and have type 6 is for BVI (Cisco Bridge Virtual Interface) on Cisco AP AIR-SAPxxxxx

```
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
              <MAC>xx:xx:xx:xx:xx:xx</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>BVI1</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>xxxxxxxxx</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>19.23 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>BV1</IFNAME>
          <IFNUMBER>y</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>xxxxxxxxxx</IFOUTOCTETS>
          <IFSPEED>54000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <IP>yyy.yyy.yyy.yyy</IP>
          <IPS>
            <IP>yyy.yyy.yyy.yyy</IP>
          </IPS>
          <MAC>xx:xx:xx:xx:xx:xx</MAC>
        </PORT>
```

**Pull request closed without merging**
