### PR TITLE
Glpi0.90 Alert when changing some inventory items

### PR DESCRIPTION
**Pull request by guillermohaad**
We had stolen fusion memory modules but not to report this change me.
urgent serious to create a plugin for this alert.

### CODE REVIEW

**Comment by ddurieux** [comment]
you need:

* rebase on master
* you have changes have yet in master, so will not merge in this state
* you have more changes than only alert on inventory changes like said in title/description of PR

**Comment by guillermohaad** [comment]
Hi friend @ddurieux , 
I apologize but I do not understand what you say, or maybe not know me explain?
we were the victim of theft and glpi memory modules do not report this alert.
We have serious trouble for this, is there any way to know about this news?

**Comment by ddurieux** [comment]
Not understand this commit and the message you sent

**Comment by guillermohaad** [comment]
my apologies friend, sorry for my English is very bad.
when you say this you mean?
you need:

rebase on master
You have Changes have yet in master, so will not merge in esta state
You have more than only alert on Changes Changes like Said inventory in title / description of PR

**Comment by trasher** [comment]
This is not a PR, I'm closing.

@guillermohaad as far as I understand, you want a new feature to be added; please use http://fusioninventory.userecho.com/ to ask for new features, and please be more precise/descriptive about what you want.

**Pull request closed without merging**
