### PR TITLE
teamviewer id clickable

### PR DESCRIPTION
**Pull request by Dayflare**
start teamviewer connection directly from glpi computer interface

https://start.teamviewer.com/id directly connects to the id with the local installed teamviewer client.

this is my very first pr, i hope everything is fine :)

### CODE REVIEW

**Comment by AnaelMobilia** [comment]
This PR close #2557 

@Dayflare you need to fix some spaces left :
FILE: ...ninventory/glpi/plugins/fusioninventory/inc/inventorycomputerlib.class.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 1085 | ERROR | [x] Expected 1 space(s) after closing parenthesis; found
      |       |     newline
 1126 | ERROR | [x] Expected 1 space(s) after closing parenthesis; found
      |       |     newline

Regards

**Comment by Dayflare** [comment]
@AnaelMobilia i looked into this. If i see this right, my PR needs a rebase, the admin of this repo can do this while merging. (Rebase and Merge) Thats why Travis fails because it's missing some important bugfix commits.

i tested my little code several weeks in production, it works fine.

**Comment by ddurieux** [comment]
Thanks for your contribution ;)

**Comment by Rutaa** [comment]
how to install it

**Comment by Dayflare** [comment]
@Rutaa you need to wait for the next release, but if you confident enough you can edit the sourcecode yourself.

**Pull request merged**
