### PR TITLE
purge agent on computer purge when no task associated

### PR DESCRIPTION
**Pull request by orthagh**
Following the irc discussion

### CODE REVIEW

**Comment by trasher** [comment]
Tests are failing ;)

**Comment by ddurieux** [comment]
I'm not agree, delete the taskjobstates based on agents_id can be very long and it's not a good idea to make it here. Perhaps add a cron task to clean this the night

**Comment by orthagh** [comment]
we don't delete taskjobstates, we delete agent if no taskjobstates exist for it

**Comment by ddurieux** [comment]
Ok, you're right, but use limit 1 in `$states = $pfTaskjobstate->find(...` it will prevent get all lines when have very too many ;)

**Comment by orthagh** [comment]
ok, good point, i push a pr this morning for that

**Pull request merged**
