### PR TITLE
[wip] Fix tests

### PR DESCRIPTION
**Pull request by cedric-anne**

### CODE REVIEW

**Comment by cedric-anne** [comment]
Tests were OK without native SQL type (with a GLPI version prior to changes mades on domains). See https://travis-ci.org/fusioninventory/fusioninventory-for-glpi/builds/642949574 (commit https://github.com/fusioninventory/fusioninventory-for-glpi/tree/73a7ea0be8c9f4ffc6e7ec559aa7669e6ab3c280 )

**Comment by cedric-anne** [comment]
And tests are now failing after putting back native SQL type. See https://travis-ci.org/fusioninventory/fusioninventory-for-glpi/builds/642965984

**Comment by trasher** [comment]
Did you see there are a few notices before failing tests? (quite hard to see in the middle of all output)

**Comment by cedric-anne** [comment]
Yes, I saw them. But it does not really give clue about the source problem.
It seems that networkports are not created/updated correctly, but I did not find why.

**Pull request closed without merging**
