### PR TITLE
0.85/collapse tasks in monitoring / logs

### PR DESCRIPTION
**Pull request by orthagh**
proposal for http://forge.fusioninventory.org/issues/2901

### CODE REVIEW

**Comment by ddurieux** [comment]
Feature is a good idea, but when refresh all 5 secondes, the task expanded before is collapsed after each refresh

**Comment by orthagh** [comment]
ok good point, i'll check this this week

**Comment by orthagh** [comment]
Here (and rebased)

**Comment by ddurieux** [comment]
related #1632

**Pull request merged**
