### PR TITLE
add kernel_version to computer inventory

### PR DESCRIPTION
**Pull request by orthagh**
Corresponding GLPI PR : https://github.com/glpi-project/glpi/pull/373

### CODE REVIEW

**Comment by ddurieux** [comment]
Can you rebase with master please? I have made modifications with travis (unit tests).
``` git rebase master ```

**Comment by ddurieux** [comment]
Waiting it's integrated in GLPI master branch

**Comment by orthagh** [comment]
merged in glpi-project/glpi@d90de29040f03d48edfb51173b070fa712d61d03

**Comment by ddurieux** [comment]
We manage it in plugin fusioninventory, see #1295

**Pull request closed without merging**
