### PR TITLE
Glpi9.2 Power Supplies

### PR DESCRIPTION
**Pull request by po1vo**
Fusioninventory should now be able to accept Power Supplies from the agent.

### CODE REVIEW

**Comment by wawax** [comment]
Hi @po1vo 
Thank for your pull request.
The agent doesn't retrieve informations about POWERSUPPLIES (we only retrieve batteries informations).

Which agent do you use ? how did you get this information ?

**Comment by po1vo** [comment]
I know the agent does not retrieve power supplies information yet. So i created patches for the agent: https://github.com/fusioninventory/fusioninventory-agent/pull/389

**Comment by wawax** [comment]
hi @po1vo thanks a lot !
we've currently working hard on implementing datacenters in GLPI https://github.com/glpi-project/spec/wiki/GLPI-Datacenters-management 
Power management is definitly in the scope, so we're going to look closely to your PR in the coming weeks :)

**Comment by wawax** [comment]
Hi
Let's check the agent patch first with @g-bougard . As PDUs have been added to GLPI 9.3, I prefer that you rebase your code to master and push again to update the pull request (you may have some conflicts).

Thanks!

**Comment by trasher** [comment]
GLPI 9.3 is currently the master branch of the GLPI repository; it's not been released yet.

**Comment by trasher** [comment]
As of the rebase; yes, your PR should reach master branch of the current repo :)

**Pull request closed without merging**
