### PR TITLE
Use core antivirus stuff

### PR DESCRIPTION
**Pull request by trasher**
Since antivirus stuff do exists in GLPI core, we no longer need specific code in the plugin for that now.

### CODE REVIEW

**Comment by ddurieux** [comment]
1/ don't rename fields on migration, because you will drop after, so it will use times for that and not performant

2/ we need add some tests about antivirus add / update from inventory received

**Comment by trasher** [comment]
You're right, I'll drop the rename :)

And, OK, I'll work on some unit tests.

**Comment by trasher** [comment]
I've drop the rename of the fields, and I've added some unit tests. Lemme know if it sounds good to you ;)

**Comment by ddurieux** [comment]
yep it's ok ;)

Thanks

**Comment by trasher** [comment]
Great, thank you :)

**Pull request merged**
